Solution
mate-academy/react_dynamic-list-of-todos pull request #1019
Opened 2022-08-25 04:48 UTC by LovelyDrug

[DEMO LINK](https://LovelyDrug.github.io/react_dynamic-list-of-todos/)

2022-08-30 11:50 UTC, blcts approved these changes
nice

2022-08-30 12:45 UTC, VETALEK requested changes
GJ 👍 
commented

2022-08-30 12:45 UTC, VETALEK commented on src/App.tsx
> +  const getFilter = (option: string) => {
missed `useCallback` here

2022-08-30 12:45 UTC, VETALEK commented on src/components/TodoModal/TodoModal.tsx
> +  const getSelectedTodo = () => {
`useCallback`

2022-08-31 09:45 UTC, VETALEK approved these changes
🔥

2022-08-31 11:03 UTC, closed without merging