solution
mate-academy/react_dynamic-list-of-todos pull request #1034
Opened 2022-09-14 09:28 UTC by victorgri

2022-09-14 09:28 UTC, victorgri commented
https://victorgri.github.io/react_dynamic-list-of-todos/

2022-09-17 07:17 UTC, SanyaBratashchuk requested changes

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/App.tsx
> +};
move it to the utils folder

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/App.tsx
> +  const [filter, setFilter] = useState('all');
create enum for filter options

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/App.tsx
> +      .then(todosList => setTodos(todosList));
```suggestion
      .then(setTodos);
```

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/App.tsx
> +  }, [todos]);
why do you need todos in an array of dependencies?

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/App.tsx
> +    });
if it is a clear function you can move it out from the component

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/App.tsx
> +              )}
You can simplify it `filteringTodos ? todoList : Loader`

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/App.tsx
> +          setSelectedTodo={() => setSelectedTodo(null)}
```suggestion
          onClose={() => setSelectedTodo(null)}
```

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/components/TodoFilter/TodoFilter.tsx
> +  setQuery: (query: string) => void,
```suggestion
  setQuery: React.Dispatch<React.SetStateAction<string>>,
```

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/components/TodoFilter/TodoFilter.tsx
> +          }}
move it to the separate function

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/components/TodoFilter/TodoFilter.tsx
> +              }}
move it to the separate function

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/components/TodoList/TodoList.tsx
> +  setSelectedTodo: (todo: Todo) => void,
the same use more specific types

2022-09-17 07:17 UTC, SanyaBratashchuk commented on src/components/TodoModal/TodoModal.tsx
> +      .then(user => setSelectedUser(user));
```suggestion
      .then(setSelectedUser);
```

2023-10-17 11:03 UTC, closed without merging