React dynamic list of TODOs
mate-academy/react_dynamic-list-of-todos pull request #1130
Opened 2022-11-01 13:02 UTC by Vladosik1337

[DEMO LINK](https://Vladosik1337.github.io/react_dynamic-list-of-todos/)

2022-11-02 14:49 UTC, artem-musii approved these changes
GJ!

2022-11-03 09:20 UTC, Anna-Tkachenko requested changes

2022-11-03 09:20 UTC, Anna-Tkachenko commented on src/App.tsx
> +  const [filteredSelect, setFilteredSelect] = useState('all');
use enum for available values for this field

2022-11-03 09:20 UTC, Anna-Tkachenko commented on src/App.tsx
> +  const todosId = (todoId: number) => {
todosId variable should store some number
now it stores the function, check variable name

2022-11-03 09:20 UTC, Anna-Tkachenko commented on src/App.tsx
> +              {visibleTodos.length === 0 && <Loader />}
will be better to create separate variable for defining was data loaded or no
for now if you'll receive an empty array from the server, user will see infinite loader

2022-11-03 09:20 UTC, Anna-Tkachenko commented on src/App.tsx
> +          todo={todosId(selectedTodo) || null}
move returning null value inside the function for getting todo

2022-11-03 09:20 UTC, Anna-Tkachenko commented on src/components/TodoList/TodoList.tsx
> +      <tbody>
you shouldn't render tbody for each todo
tbody should be only one in table

2022-11-03 09:20 UTC, Anna-Tkachenko commented on src/components/TodoList/TodoList.tsx
> +            'has-background-info-light': todo.id === selectedTodo,
you check is current todo selected several times
create separate boolean variable for this value inside map callback

2022-11-03 09:20 UTC, Anna-Tkachenko commented on src/components/TodoModal/TodoModal.tsx
> +      {(!user || !todo) ? (
same here about loader, will be better to create separate variable for handling was data loaded or no

2022-11-04 14:37 UTC, Anna-Tkachenko requested changes
You didn't add any commits after my previous comments

2022-11-07 10:08 UTC, Denchepornyuk requested changes

2022-11-07 10:08 UTC, Denchepornyuk commented on src/App.tsx
> +  const [filteredSelect, setFilteredSelect] = useState(TodosStatus.All);
add type for the useState - `filteredSelect`

2022-11-07 10:08 UTC, Denchepornyuk commented on src/App.tsx
> +                  setSelectedTodo={setSelectedTodo}
the same here

2022-11-07 10:08 UTC, Denchepornyuk commented on src/components/TodoList/TodoList.tsx
>          </td>
do you need an empty tag here? Let's use `&&` instead of ternary operator

2022-11-07 10:08 UTC, Denchepornyuk commented on src/components/TodoModal/TodoModal.tsx
> +        setUser(userFromServer);
what if setUser return an error? You should catch an error here

2022-11-07 10:08 UTC, Denchepornyuk commented on src/types/TodosStatus.ts
> +}
add empty line at the end of the file

2022-11-07 11:24 UTC, Denchepornyuk approved these changes

2025-11-08 12:31 UTC, closed without merging