solution
mate-academy/react_dynamic-list-of-todos pull request #1217
Opened 2022-12-09 18:27 UTC by mitattt

[DEMO LINK](https://mitattt.github.io/react_dynamic-list-of-todos/)

2022-12-09 19:00 UTC, spiritkyiv requested changes

2022-12-09 19:00 UTC, spiritkyiv commented on src/components/TodoList/TodoList.tsx
> +                  <span className="icon" data-cy="iconCompleted">
i think, you can nest tarnar opperator inside <td className="is-vcentered">

2022-12-09 19:00 UTC, spiritkyiv commented on src/components/TodoModal/TodoModal.tsx
>                <a href="mailto:Sincere@april.biz">
you forgot to set emeil from current todo

2022-12-09 19:08 UTC, spiritkyiv commented on src/components/TodoList/TodoList.tsx
> +                  <span className="icon" data-cy="iconCompleted">
inside <td className="is-vcentered">

2022-12-09 19:18 UTC, spiritkyiv approved these changes
Looks good

2022-12-13 06:25 UTC, Olexandr6 approved these changes
Well done 🔥 Great job!

2022-12-13 06:25 UTC, Olexandr6 commented on src/App.tsx
> +  const [status, setStatus] = useState('all');
Use enum for `status`

2022-12-13 06:25 UTC, Olexandr6 commented on src/App.tsx
> +  }, []);
🔥

2025-01-16 21:03 UTC, closed without merging