Solution
mate-academy/react_dynamic-list-of-todos pull request #1243
Opened 2022-12-23 22:24 UTC by Ivanenko1402

[DEMO LINK](https://Ivanenko1402.github.io/react_dynamic-list-of-todos/)

2022-12-24 11:46 UTC, Anastasiia-Svintsova requested changes
- Try to pass all the tests 
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/99403198/209434415-7d816c88-9e89-400f-adf0-ce1f9b6b4ea9.png">

2022-12-24 11:46 UTC, Anastasiia-Svintsova commented on src/App.tsx
>  /* eslint-disable max-len */
Remove this line

2022-12-24 11:46 UTC, Anastasiia-Svintsova commented on src/App.tsx
> +        break;
You do the same actions here. Combine it

2022-12-24 11:46 UTC, Anastasiia-Svintsova commented on src/App.tsx
> +              )}
Use a ternary operator here

2022-12-24 11:46 UTC, Anastasiia-Svintsova commented on src/App.tsx
> +      case 'active':
Create an enum for filter types

2022-12-24 11:46 UTC, Anastasiia-Svintsova commented on src/components/TodoFilter/TodoFilter.tsx
> +          {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
Don't disable eslint. Try to solve the error

2022-12-25 13:19 UTC, polosanya approved these changes
Good job! I'm approving it, but please pay attention to my comments

2022-12-25 13:19 UTC, polosanya commented on src/App.tsx
> +}
```suggestion
enum Options {
  Active = 'active',
  Completed = 'completed',
  All = 'all',
}
```
Enum keys should be capitalized

2022-12-25 13:19 UTC, polosanya commented on src/App.tsx
> +    getTodos().then(items => setTodosFromServer(items));
Would be great to catch a possible error too

2022-12-25 13:19 UTC, polosanya commented on src/App.tsx
> +                ) : <Loader />}
```suggestion
                ) 
                : <Loader />}
```

2026-03-02 13:10 UTC, closed without merging