solution
mate-academy/react_dynamic-list-of-todos pull request #1273
Opened 2023-01-16 19:46 UTC by official-artem

[DEMO LINK](https://official-artem.github.io/react_dynamic-list-of-todos/)

2023-01-18 11:02 UTC, Nazar-Brunarskyi approved these changes

2023-01-18 11:02 UTC, Nazar-Brunarskyi commented on src/components/TodoModal/TodoModal.tsx
> +                    : 'has-text-danger'
use classNames here

2023-01-18 11:02 UTC, Nazar-Brunarskyi commented on src/components/TodoList/TodoList.tsx
> +                }>
use classNames here

2023-01-18 14:19 UTC, solaryasha requested changes

2023-01-18 14:19 UTC, solaryasha commented on src/App.tsx
> +  };
Wrap the callback with the `useCallback`, cause you are passing this callback to the another component.

2023-01-18 14:19 UTC, solaryasha commented on src/components/TodoList/TodoList.tsx
> +  onCLick: (todoId: number) => void;
I have no idea what this `onClick` actually does, let's use better naming

2023-01-18 14:19 UTC, solaryasha commented on src/components/TodoModal/TodoModal.tsx
> +    };
Why do we need this wrapper?

2023-01-18 14:19 UTC, solaryasha commented on src/tools/GetTodos.ts
> +export const getTodo = async (todoId: number) => {
```suggestion
export const getTodoById = async (todoId: number) => {
```

2023-01-18 14:19 UTC, solaryasha commented on src/tools/GetTodos.ts
> +export function getUserInfo(userId: number | undefined): Promise<User> {
```suggestion
export function getUserById(userId: number | undefined): Promise<User> {
```

2023-01-19 09:34 UTC, valerii-derkach approved these changes

2023-01-19 09:34 UTC, valerii-derkach commented on src/tools/GetTodos.ts
> +export const getTodo = async (todoId: number) => {
fix it

2023-04-19 09:04 UTC, solaryasha approved these changes

2026-03-01 23:24 UTC, closed without merging