solution
mate-academy/react_dynamic-list-of-todos pull request #1281
Opened 2023-01-19 18:32 UTC by batstolya

[DEMO LINK](https://batstolya.github.io/react_dynamic-list-of-todos/)

2023-01-23 13:07 UTC, anastasiia-bilska requested changes
Good job! Please my comments. It would be great if you could optimize your code a bit :)

2023-01-23 13:07 UTC, anastasiia-bilska commented on src/components/TodoModal/TodoModal.tsx
> +export const TodoModal: React.FC<Props> = ({ onCloseModal, todo }) => {
please add the ```React.memo```

2023-01-23 13:07 UTC, anastasiia-bilska commented on src/components/TodoFilter/TodoFilter.tsx
> +export const TodoFilter: React.FC<Props> = ({
please add the ```React.memo```

2023-01-23 19:33 UTC, anastasiia-bilska approved these changes
Good job!

2023-01-23 19:33 UTC, anastasiia-bilska commented on src/App.tsx
> +  const [selectedTodoId, setSelectedTodoId] = useState<number>(0);
No need to specify type here :)

2023-01-24 12:45 UTC, Ihor-Karpyn requested changes

2023-01-24 12:45 UTC, Ihor-Karpyn commented on src/App.tsx
> +  const [option, setOption] = useState('all');
https://mateacademy.slack.com/archives/C048KMNGNKU/p1674562302147209
https://mateacademy.slack.com/archives/C048KMNGNKU/p1674563959824619

2023-01-24 12:45 UTC, Ihor-Karpyn commented on src/App.tsx
> +  }), [option, visibleTodos]);
Better to move huge part of code to function in separate file

2023-01-24 12:45 UTC, Ihor-Karpyn commented on src/App.tsx
> +                onQuery={setQuery}
on query what?

2023-01-24 12:45 UTC, Ihor-Karpyn commented on src/App.tsx
> +                  onUserId={setSelectedTodoId}
on userId what?

2023-01-25 15:16 UTC, Ihor-Karpyn approved these changes
Amazing, keep it up 🚀

2026-07-13 23:08 UTC, closed without merging