Solution
mate-academy/react_dynamic-list-of-todos pull request #1354
Opened 2023-02-12 22:28 UTC by vlad-boikov

[DEMO LINK](https://vlad-boikov.github.io/react_dynamic-list-of-todos/)

2023-02-13 16:27 UTC, slavanosatskyi requested changes
well done, although there are some places to be fixed

Please, pay attention that todo list header is visible during loading of todo list. It should be hidden during loading according to example https://mate-academy.github.io/react_dynamic-list-of-todos/
![Screenshot 2023-02-13 at 18 07 33](https://user-images.githubusercontent.com/6526149/218514568-9dafe18b-2dac-46ab-af66-f002e1cc030f.png)

2023-02-13 16:27 UTC, slavanosatskyi commented on src/App.tsx
> +      setLoading(false);
What happens if promise finishes with negative result (server error, disconnected, etc)? what will happen to your loading state? (hint, consider to add catch handler here)

2023-02-13 18:47 UTC, Viktor-Kost requested changes
Nice job!)
Left a few comments

2023-02-13 18:47 UTC, Viktor-Kost commented on src/App.tsx
> +      });
`throw new Error('Uploading error');` make sense to use if you have some conditions at `.then` statement and wanna  throw an Error that you catch at `.catch` statement

Also you need to stop your loader not depends on result
```suggestion
      .then(result => {
        setTodos(result);
      })
      .catch((error) => {
        console.error(error)
      })
      .finally(() => {
        setLoading(false);
      });
```

2023-02-13 18:47 UTC, Viktor-Kost commented on src/App.tsx
> +    const completed = filteredQuery.filter(todo => todo.completed);
It would be better to apply `useMemo` if you've already know this hook

2023-02-13 18:47 UTC, Viktor-Kost commented on src/components/TodoList/TodoList.tsx
> +              selectedItem && selectedItem.id === todo.id,
```suggestion
              selectedItem?.id === todo.id,
```

2023-02-13 18:47 UTC, Viktor-Kost commented on src/components/TodoList/TodoList.tsx
> +                    selectedItem && selectedItem.id === todo.id
```suggestion
                    selectedItem?.id === todo.id
```

2023-02-13 18:53 UTC, ivbutsykin requested changes

2023-02-13 18:53 UTC, ivbutsykin commented on src/App.tsx
> +  const [filter, setFilter] = useState('all');
Create filter types (enum or simple constants) and move it in separate file:
```
const FILTER = { 
  ALL: 'all',
  ...
}
```

2023-02-13 18:53 UTC, ivbutsykin commented on src/App.tsx
> +        setLoading(false);
Move `setLoading` in finally: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

2023-02-13 18:53 UTC, ivbutsykin commented on src/App.tsx
> +  const filterHandler = (
I think it's not `filterHandler`, it's more `filterTodos`. Also will be nice to wrap it in `useCallback` hook

2023-02-13 18:53 UTC, ivbutsykin commented on src/App.tsx
> +  const visibleTodos = filterHandler(filter, query, todos);
And this wrap in `useMemo`

2023-02-13 18:53 UTC, ivbutsykin commented on src/components/TodoFilter/TodoFilter.tsx
> +        {query && (
It's not a boolean, so better to add `!!`

2023-02-14 10:26 UTC, DarkMistyRoom requested changes

2023-02-14 10:26 UTC, DarkMistyRoom commented on src/App.tsx
> +        console.error(error);
better to show some message to a user

2023-02-14 10:26 UTC, DarkMistyRoom commented on src/components/TodoList/TodoList.tsx
> +  loading: boolean,
```suggestion
  isLoading: boolean,
```

2023-02-14 10:26 UTC, DarkMistyRoom commented on src/components/TodoList/TodoList.tsx
> +  loading: boolean,
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2023-02-14 15:58 UTC, Volodymyr-Melnyk-Fron10der requested changes
Hi, smth wrong with api request here 
![image](https://user-images.githubusercontent.com/122989585/218789740-53ae7d3b-e718-4e6f-b714-bc1b698a8e74.png)

2023-02-14 15:58 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/TodoList/TodoList.tsx
> +  isLoading: loading,
Why did you rename it?) there are no conflicts with other variables

2023-02-14 15:58 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/TodoList/TodoList.tsx
> +            >
It looks more simple
```suggestion
            <p className={todo.completed ? 'has-text-success' : 'has-text-danger'} >
```

2023-02-14 15:58 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/TodoList/TodoList.tsx
> +                  }
same here

2023-02-14 15:58 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/TodoModal/TodoModal.tsx
> +  });
```suggestion
  useEffect(() => {
    getUser(selectedItem.userId).then(user=> setUser(user));
  }, []);
```

2023-02-15 08:27 UTC, vlad-demchuk approved these changes

2025-02-28 07:41 UTC, closed without merging