dynamic list
mate-academy/react_dynamic-list-of-todos pull request #1492
Opened 2023-04-11 12:13 UTC by VadimDrobyazko

[DEMO LINK](https://vadimdrobyazko.github.io/react_dynamic-list-of-todos/)

2023-04-11 13:55 UTC, mykhalenych requested changes

2023-04-11 13:55 UTC, mykhalenych commented on src/components/TodoModal/TodoModal.tsx
> +    getUser(selectTodo.userId)
The useEffect is missing a dependency on 'selectTodo.userId'. Add it to the dependency array

2023-04-11 13:55 UTC, mykhalenych commented on src/App.tsx
> +        case 'all':
create enum with all, completed, active

2023-04-11 13:55 UTC, mykhalenych commented on src/App.tsx
> +  const [selectTodo, setSelectTodo] = useState<Todo | null>(null);
better will be isLoading and selectedTodo

2023-04-11 16:36 UTC, Viktor-Kost approved these changes
Looks very good!
I left some recommendation how you could improve your code more

2023-04-11 16:36 UTC, Viktor-Kost commented on src/components/TodoList/TodoList.tsx
> +          <tr
I would recommend to create a Component `TodoItem` and use it for this map

2023-04-11 16:36 UTC, Viktor-Kost commented on src/App.tsx
> +  }, [selectedTodo?.userId]);
as a recommendations (good practice): 
1) use async/await
2) handle errors (at least with a console)

```
useEffect(() => {
  const fetchData = async () => {
    try {
      setIsLoading(true);
      const todos = await getTodos();
      setTodos(todos);
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  fetchData();
}, [selectedTodo?.userId]);


```

2023-04-11 16:36 UTC, Viktor-Kost commented on src/components/TodoModal/TodoModal.tsx
> +              {`Todo #${selectedTodo.id}`}
as a recommendation: 
use object destructuring for `selectedTodo`

2023-04-12 11:12 UTC, ivadimko commented on src/components/TodoModal/TodoModal.tsx
> +      {!currentUser || !selectedTodo ? (
Replace `!currentUser || !selectedTodo` with `!currentUser` in the conditional since `selectedTodo` will always be truthy inside the component.

2023-04-12 11:12 UTC, ivadimko commented on src/components/TodoModal/TodoModal.tsx
> -              Todo #2
Replace `{`Todo #${selectedTodo}`}` with `{`Todo #${selectedTodo.id}`}` to display the correct Todo ID in the modal header.

2024-04-03 07:52 UTC, closed without merging