add dynamic-list-of-todos
mate-academy/react_dynamic-list-of-todos pull request #1635
Opened 2023-06-12 13:50 UTC by DidenkoDenis306

[DEMO LINK](https://DidenkoDenis306.github.io/react_dynamic-list-of-todos/)

2023-06-22 10:58 UTC, And678 requested changes
Good job, but when pressing enter on your input, the page needlessly reloads. Try using `event.preventDefault()` on form submit

2023-06-22 11:06 UTC, dffUqp requested changes
LGTM but needs a few fixes:smiley:

2023-06-22 11:06 UTC, dffUqp commented on src/components/TodoFilter/TodoFilter.tsx
> +            {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
let's fix this eslint issue:smiley:

2023-06-22 11:06 UTC, dffUqp commented on src/components/TodoList/TodoList.tsx
> +                )}
I think here we change only icon, so let's replace this huge part of code with [classnames](https://www.npmjs.com/package/classnames) library

2023-06-28 07:57 UTC, 33Orange approved these changes
Well done

2024-07-09 10:14 UTC, closed without merging