Solution
mate-academy/react_dynamic-list-of-todos pull request #1649
Opened 2023-06-28 12:48 UTC by amashutikov

[DEMO LINK](https://amashutikov.github.io/react_dynamic-list-of-todos/)

2023-06-28 15:23 UTC, AlexKherson requested changes
Good job!

2023-06-28 15:23 UTC, AlexKherson commented on src/App.tsx
> +    ));
you can skip to filter if you have an empty query and selected all

2023-06-28 15:54 UTC, bohdan-mykhailenko approved these changes
Good job 👍
Here are some points to refactor code to improve readability

2023-06-28 15:54 UTC, bohdan-mykhailenko commented on src/components/TodoFilter/TodoFilter.tsx
> +        onChange={(event) => onQueryChange(event.target.value)}
The same is here

2023-06-28 15:54 UTC, bohdan-mykhailenko commented on src/components/TodoList/TodoList.tsx
> +                  onClick={() => onChoose(todo.id)}
Here is the same issue without handler

2023-06-29 08:00 UTC, dinaminahi requested changes
Good job 👍 
Few fixes needed

2023-06-29 08:00 UTC, dinaminahi commented on src/App.tsx
> +      <TodoModal
Let's remove the modal from DOM when it closes
```suggestion
  {  selectedTodoId && <TodoModal
```

2023-06-29 08:00 UTC, dinaminahi commented on src/components/TodoFilter/TodoFilter.tsx
> +          onChange={(event) => onFilterChange(event.target.value)}
Let's accept event in already existing function `handleFilterChange`, so we don't need to create a new arrow function here

2023-06-29 08:00 UTC, dinaminahi commented on src/components/TodoFilter/TodoFilter.tsx
> +          onChange={(event) => onFilterChange(event.target.value)}
Let's accept event in already existing function `handleFilterChange`, so we don't need to create a new arrow function here
```suggestion
          onChange={onFilterChange}
          
```

2023-06-29 08:00 UTC, dinaminahi commented on src/components/TodoFilter/TodoFilter.tsx
> +        onChange={(event) => onQueryChange(event.target.value)}
same here

2023-06-29 08:00 UTC, dinaminahi commented on src/App.tsx
> +  const selectedTodo = visibleTodos.find(todo => todo.id === selectedTodoId) || null;
Maybe we can set full todo in the state instead of only id, to not search it every time?

2023-06-29 08:00 UTC, dinaminahi commented on src/App.tsx
> +  const visibleTodos = filter !== 'all' || query
Let's create enum for the todo statuses: 'all', 'completed', 'active'

2023-06-29 08:00 UTC, dinaminahi commented on src/App.tsx
> +                    onChoose={handleTodoSelect}
Look through your naming, use descriptive names
```suggestion
                    onTodoSelect={handleTodoSelect}
```

2023-07-03 08:36 UTC, 33Orange requested changes
Almost done

A few momets to improve and fix your code

2023-07-03 08:36 UTC, 33Orange commented on src/helpers.tsx
> +      case 'completed':
Let's use you enum values here
```suggestion
      case Filters.Completed:
```

2023-07-03 08:36 UTC, 33Orange commented on src/helpers.tsx
> +    ));
1. You create `query.toLowerCase().trim()` every iteration 
2. You can move this logic to the first filter instead of creating a new one

2023-07-03 08:36 UTC, 33Orange commented on src/App.tsx
> +    : todosFromServer;
1. Add `Filter.All` case to `filterTodos`.
2. Wrap it in `useMemo`

2023-07-03 08:36 UTC, 33Orange commented on src/App.tsx
> +  };
Move this handler to your TodoFilter component and provide only `setFilter` from the app

2023-07-03 08:36 UTC, 33Orange commented on src/App.tsx
> +  };
Create these handlers inside your `TodoFilter` component nad provide only `setQuery` from the app

2023-07-03 08:36 UTC, 33Orange commented on src/components/TodoFilter/TodoFilter.tsx
> +          <option value="completed">Completed</option> */}
Remove redundant comments

2023-07-03 08:36 UTC, 33Orange commented on src/components/TodoFilter/TodoFilter.tsx
> +          {(Object.keys(Filters) as Array<keyof typeof Filters>).map(key => (
You can use `Object.entries` instead to improve readability 
```suggestion
          {Object.entries(ListStyle).forEach(([key, value]) => (
```

2023-07-03 08:36 UTC, 33Orange commented on src/components/TodoFilter/TodoFilter.tsx
> +          // eslint-disable-next-line jsx-a11y/control-has-associated-label
Add a aria-label to the button and remove this rule disabler

2023-07-03 08:36 UTC, 33Orange commented on src/components/TodoList/TodoList.tsx
> +          );
Create a new component for todo items
```suggestion
          return (
            <TodoItem 
              ..some props
            />
          );
```

2023-07-03 08:36 UTC, 33Orange commented on src/components/TodoModal/TodoModal.tsx
> +    if (selectedTodo) {
Is it necessary here?
You render this component **ONLY** when you have `selectedTodo`

2023-07-04 12:33 UTC, 33Orange requested changes
Well done

A few moments to improve and it will be perfect

2023-07-04 12:33 UTC, 33Orange commented on src/helpers.tsx
> +};
Check my prev comment. 
Remove second filter

```suggestion
export const filterTodos = (
  todos: Todo[],
  filter: string,
  query: string,
) => {
  const optimizedQuery = query.toLowerCase().trim();

  return todos.filter(todo => {
    const isTitleIncludeQuery = todo.title.toLowerCase().includes(optimizedQuery);
    switch (filter) {
      case Filters.All:
        return isTitleIncludeQuery;
      case Filters.Completed:
        return todo.completed && isTitleIncludeQuery;
      case Filters.Active:
        return !todo.completed && isTitleIncludeQuery;
      default:
        return todo;
    }
  })
};
```

2023-07-04 12:33 UTC, 33Orange commented on src/components/TodoList/TodoList.tsx
> +            />
Remove return 
```suggestion
            <TodoItem
              todo={todo}
              isTodoSelected={todo.id === selectedTodoId}
              onTodoSelect={onTodoSelect}
              key={todo.id}
            />
```

2023-07-04 12:33 UTC, 33Orange commented on src/components/TodoModal/TodoModal.tsx
> +
Use destructuring assignment for selectedTodo here

2023-07-11 08:39 UTC, naziamoff commented on src/components/TodoFilter/TodoFilter.tsx
> +  };
from your names of the functions i don't get **at all** what do these functions do. + they are at the top level, so it takes a while for the reader to understand what's happening here. It shouldn't be like that

2023-07-11 08:39 UTC, naziamoff commented on src/components/TodoFilter/TodoFilter.tsx
> +
```suggestion
```

2023-07-11 08:40 UTC, naziamoff commented on src/components/TodoItem/TodoItem.tsx
> +          'has-text-danger': !todo.completed,
one classname can serve as a default one. It will be overwritten if matches other condition

2023-07-11 08:40 UTC, naziamoff commented on src/helpers.tsx
> +  const optimizedQuery = query.toLowerCase().trim();
I would say `normalized`, not `optimized`

2023-07-11 08:41 UTC, naziamoff commented on src/helpers.tsx
> +    ));
seems this action is repeated and your filter callback already contains this functionality

2023-07-24 13:04 UTC, naziamoff approved these changes
🔥

2023-11-29 15:46 UTC, closed without merging