Solution
mate-academy/react_dynamic-list-of-todos pull request #1666
Opened 2023-06-30 05:31 UTC by skinnyjazz

[DEMO LINK](https://skinnyjazz.github.io/react_dynamic-list-of-todos/)

2023-07-02 14:14 UTC, Yuliia-kucheriavenko approved these changes

2023-07-02 15:36 UTC, YeMyr approved these changes

2023-07-02 17:50 UTC, RoksolanaTylipska approved these changes

2023-07-05 12:23 UTC, dffUqp requested changes
A lot of falling tests. Try to fix it:upside_down_face:

2023-07-05 12:51 UTC, skinnyjazz commented
> A lot of falling tests. Try to fix it🙃

2023-07-05 12:51 UTC, closed without merging