solution
mate-academy/react_dynamic-list-of-todos pull request #1692
Opened 2023-07-07 14:59 UTC by MaxSchmide

[DEMO LINK](https://maxschmide.github.io/react_dynamic-list-of-todos/)

2023-07-09 12:50 UTC, ollavka approved these changes

2023-07-13 09:16 UTC, anstsot requested changes
Great job, let's just add small improvements (`enum` for `filterStatus` and use `useMemo`)

2023-07-13 09:16 UTC, anstsot commented on src/App.tsx
> +  const { isLoading, showModal } = useTodoContext();
you're using the context, that's great :+1:
it's not very necessary especially in this task because you can use simpler logic but looks great

2023-07-13 09:16 UTC, anstsot commented on src/context/TodoContext.tsx
> +  const providingValues = {
it will be good to use `useMemo`

2023-07-13 09:16 UTC, anstsot commented on src/components/TodoFilter/TodoFilter.tsx
> +  const [filterStatus, setFilterStatus] = useState('all');
it will be good to use `enum` for `filterStatus`

2023-07-14 09:08 UTC, anstsot approved these changes
Good work, approving:sparkles:

2023-07-14 09:08 UTC, anstsot commented on src/context/TodoContext.tsx
> +  ]);
```suggestion
  const providingValues = useMemo(() => {
    todos,
    isLoading,
    selectedTodo,
    showModal,
    isUserPending,
    filterTodosByField,
    onSelect: handleSelectTodo,
    closeModalWindow,
  }, [
    todos,
    isLoading,
    selectedTodo,
    showModal,
    isUserPending,
  ]);
```

2023-10-20 18:17 UTC, closed without merging