add task solution
mate-academy/react_dynamic-list-of-todos pull request #1873
Opened 2023-09-18 19:49 UTC by Vayts

[DEMO LINK](https://Vayts.github.io/react_dynamic-list-of-todos/)

2023-09-19 20:54 UTC, roman-mirzoian requested changes
Good job, but there is quite a bit of work to be done.

2023-09-19 20:54 UTC, roman-mirzoian commented on src/App.tsx
> +  filterTodos = filterTodos.filter(todo => {
The `filter` method returns a copy of the array, so you don't need to do it manually.

2023-09-19 20:54 UTC, roman-mirzoian commented on src/App.tsx
> +      });
```suggestion
  useEffect(() => {
    getTodos()
      .then(setTodos)
      .catch((error) => {
      // eslint-disable-next-line no-console
        console.error('Something bad happened!', error);
      })
      .finally(() => setLoading(false));
```

2023-09-19 20:54 UTC, roman-mirzoian commented on src/components/TodoFilter/TodoFilter.tsx
> +  const handleDelete = () => {
Handle delete of what?

2023-09-19 20:54 UTC, roman-mirzoian commented on src/components/TodoFilter/TodoFilter.tsx
> +            <span className="icon is-right" style={{ pointerEvents: 'all' }}>
Using inline styling is a bad practice, better use css.

2023-09-19 20:54 UTC, roman-mirzoian commented on src/components/TodoFilter/TodoFilter.tsx
> +              {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
Add the code so that the linter does not fight and does not disable the linter.

2023-09-19 20:54 UTC, roman-mirzoian commented on src/components/TodoList/TodoList.tsx
> +            >
```suggestion
            <tr data-cy="todo" key={todo.id}>
```

2023-09-19 20:54 UTC, roman-mirzoian commented on src/components/TodoModal/TodoModal.tsx
>              {/* eslint-disable-next-line jsx-a11y/control-has-associated-label */}
Add the code so that the linter does not fight and does not disable the linter.

2023-10-10 11:08 UTC, BudnikOleksii approved these changes
Good job 👍

2023-12-13 17:19 UTC, closed without merging