todos
mate-academy/react_dynamic-list-of-todos pull request #1940
Opened 2023-10-12 17:37 UTC by donizer

[DEMO LINK](https://donizer.github.io/react_dynamic-list-of-todos/)

2023-10-12 17:47 UTC, maxim2310 requested changes
Good work, but lets make some improvement

2023-10-12 17:47 UTC, maxim2310 commented on src/App.tsx
> +                visibleItems.length === 0
```suggestion
                !visibleItems.length
```

2023-10-12 17:47 UTC, maxim2310 commented on src/components/TodoList/TodoList.tsx
> +              .includes(query.toLowerCase()))
move it to separate func

2023-10-12 17:47 UTC, maxim2310 commented on src/components/TodoItem/TodoItem.tsx
> +    // })
remove it

2023-10-12 17:47 UTC, maxim2310 commented on src/components/TodoModal/TodoModal.tsx
> +  }, [callback]);
why do you need it separately

2023-10-12 17:47 UTC, maxim2310 commented on src/components/TodoModal/TodoModal.tsx
> +                  {`Todo #${currentItem.todo.id}`}
Would be great to use destructuring for better readability

2023-10-13 06:01 UTC, volodymyr-soltys97 approved these changes

2024-03-17 09:21 UTC, closed without merging