list of todos
mate-academy/react_dynamic-list-of-todos pull request #2165
Opened 2024-02-01 06:59 UTC by YevhenOstrovskiy

2024-02-01 14:11 UTC, YevhenOstrovskiy commented
[DEMO LINK](https://YevhenOstrovskiy.github.io/react_dynamic-list-of-todos/)

2024-02-02 16:35 UTC, olya-shyian requested changes
Very good job!💪

1. Please remove loader if there is no data (check the original working page)
![image](https://github.com/mate-academy/react_dynamic-list-of-todos/assets/91946036/4dcb58e7-97fc-4127-8929-b6c5d26b3b66)

2024-02-02 16:35 UTC, olya-shyian commented on src/App.tsx
> +  return (
there is no need to write word `return` if you don'y have any logic, just jsx

rewrite to
`= () => (`

2024-02-02 16:35 UTC, olya-shyian commented on src/components/TodoList/TodoList.tsx
> +// import { Todo } from '../../types/Todo';
please delete commented code

2024-02-02 16:35 UTC, olya-shyian commented on src/components/TodoList/TodoList.tsx
> +type Props = {};
if there is no Props, you can delete it

2024-02-02 16:35 UTC, olya-shyian commented on src/components/TodoList/TodoList.tsx
> +                selectedTodo?.id === todo.id,
please check formatting

2024-02-02 16:35 UTC, olya-shyian commented on src/components/TodoList/TodoList.tsx
> +            <td className="has-text-right is-vcentered">
don't forget about code style, please add a line between inner elements

2024-02-02 16:35 UTC, olya-shyian commented on src/components/TodoModal/TodoModal.tsx
> +                  setSelectedTodo(null);
create a reset handler for that

2024-02-02 16:35 UTC, olya-shyian commented on src/components/TodoModal/TodoModal.tsx
> +                {/* <strong className="has-text-success">Done</strong> */}
please delete commented code

2024-02-02 16:35 UTC, olya-shyian commented on src/components/TodoModal/TodoModal.tsx
> +                    'has-text-success': selectedTodo?.completed,
please use destructuring for `selectedTodo` : {completed, id, title}

2024-02-13 09:56 UTC, DanilWeda requested changes
Good job! 
Check the loader comment and some small comments. 
Thanks!

2024-02-13 09:56 UTC, DanilWeda commented on src/App.tsx
> +                query === '' && <Loader />
```suggestion
                !query && <Loader />
```
as alternative.

2024-02-13 09:56 UTC, DanilWeda commented on src/App.tsx
> +                query === '' && <Loader />
Need change. If the query is empty I see the loader, but I need to see an empty result.

2024-02-13 09:56 UTC, DanilWeda commented on src/components/TodoContext/TodoContext.tsx
> +type Props = {
use interface prefer. 
Types have unique features but the interface is best for scaling.

2024-02-13 09:56 UTC, DanilWeda commented on src/components/TodoFilter/TodoFilter.tsx
> +        { query && (
```suggestion
        { !!query && (
```
in rendering with &&  need to convert the value to boolean.

2024-02-13 09:56 UTC, DanilWeda commented on src/components/TodoList/TodoList.tsx
> +                }}
You can write handler for it

2024-02-13 09:56 UTC, DanilWeda commented on src/components/TodoModal/TodoModal.tsx
> +// import { Loader } from '../Loader';
remove commented

2024-02-15 08:24 UTC, olya-shyian approved these changes
Great!🚀

2024-09-01 16:54 UTC, closed without merging