couple tests fall
mate-academy/react_dynamic-list-of-todos pull request #2283
Opened 2024-04-02 23:15 UTC by yurovych

https://yurovych.github.io/react_dynamic-list-of-todos/

2024-04-03 06:20 UTC, etojeDenys requested changes
Якщо раптом щось із моїх коментарів тобі незрозуміло, то, будь ласка, не чекай і звертайся у чат з менторами або приходь на Q&A сесію. Обовʼязково з усім розберемось)

2024-04-03 06:20 UTC, etojeDenys commented on src/components/TodoFilter/TodoFilter.tsx
> +  useEffect(() => {
you don't need all these states here, just create two state(one for filterValue, and one for the query), move them to the App.tsx, and pass here as props the values of those states and setState functions

so this component will just change the state, you will filter the todos in the App

2024-04-03 06:20 UTC, etojeDenys commented on src/App.tsx
> +  const [todos, setTodos] = useState<Todo[]>(todosInitial);
try to simplify it using only one state

2024-04-03 06:20 UTC, etojeDenys commented on src/App.tsx
> +  const [userId, setUserId] = useState(1);
you don't need that here, move the Modal and try to simplify using only one state

2024-04-03 06:20 UTC, etojeDenys commented on src/App.tsx
> +
add here the 
```
const [selectedTodo, setSelectedTodo] = useState<Todo | null>(null)
```
and pass this state into TodoList

2024-04-03 06:20 UTC, etojeDenys commented on src/components/TodoList/TodoList.tsx
> +  };
just save the whole todo to selectedTodo state here

2024-04-03 06:20 UTC, etojeDenys commented on src/App.tsx
> +      {isModalShowed === true && <TodoModal user={user} todos={todos} />}
```suggestion
      {selectedTodo && <TodoModal todo={selectedTodo} onClose={() => setSelectedTodo(null)} />}
```
take the userId from the todo and fetch the user inside the TodoModal

2024-04-03 06:20 UTC, etojeDenys commented on src/components/context/stateContext.tsx
> +type PropsShowModal = {
it's redundant to use the context here, 'cause you don't have the props drilling problem in your code

2024-04-04 09:53 UTC, l4st1m0za approved these changes
Good job!

2025-11-05 14:03 UTC, closed without merging