solution
mate-academy/react_dynamic-list-of-todos pull request #2343
Opened 2024-05-10 10:19 UTC by maksym-kostetskyi

https://maksym-kostetskyi.github.io/react_dynamic-list-of-todos

2024-05-10 10:27 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-05-10 10:27 UTC, volodymyr-soltys97 commented on src/App.tsx
> +        if (filter === 'active') {
Сreate a enum for 'active', 'completed' and 'all' and use it everywhere

2024-05-10 10:27 UTC, volodymyr-soltys97 commented on src/App.tsx
> +              {!loading && todos.length > 0 && (
```suggestion
              {!loading && !!todos.length && (
```

2024-05-10 10:27 UTC, volodymyr-soltys97 commented on src/App.tsx
> +              {!loading && todos.length === 0 && (
```suggestion
              {!loading && !todos.length && (
```

2024-05-10 10:27 UTC, volodymyr-soltys97 commented on src/components/TodoList/TodoList.tsx
> +                !todo.completed ? 'has-text-danger' : 'has-text-success'
Use the classnames library for add classes with condition

2024-05-10 12:41 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-05-10 12:41 UTC, anastasiiavorobiova commented on src/components/TodoList/TodoList.tsx
> +          <tr data-cy="todo" className="">
Consider using keys while rendering lists

2024-05-11 13:21 UTC, GUSILLUS requested changes
GJ

2024-05-11 13:21 UTC, GUSILLUS commented on src/App.tsx
> +  const [search, setSearch] = useState('');
consider renaming to searchQuery to improve readability

2024-05-11 13:21 UTC, GUSILLUS commented on src/App.tsx
> +  const [loading, setLoading] = useState(false);
Consider renaming it to isLoading https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2024-05-11 13:21 UTC, GUSILLUS commented on src/components/TodoFilter/TodoFilter.tsx
> +  search: React.Dispatch<string>;
Consider renaming it to clarify that this is some sort of function `changeFilter` `changeSearchQuery`

2024-05-11 13:21 UTC, GUSILLUS commented on src/components/TodoFilter/TodoFilter.tsx
> +  const [input, setInput] = useState('');
You don't need this state, you can use `searchQuery` state here just pass it in props

2024-05-11 13:21 UTC, GUSILLUS commented on src/components/TodoFilter/TodoFilter.tsx
> +            <option value={Filter.completed}>Completed</option>
You can use map rendering here with enum values `Object.values(Filter)`

2024-05-11 13:21 UTC, GUSILLUS commented on src/components/TodoList/TodoList.tsx
> +          <tr data-cy="todo" key={todo.id}>
Consider creating todo item component and use destruction assignment for todo object

2024-05-12 09:48 UTC, SanyaBratashchuk requested changes

2024-05-12 09:48 UTC, SanyaBratashchuk commented on src/types/TodoType.ts
> +export interface TodoType {
```suggestion
export interface Todo {
```

2024-05-12 09:48 UTC, SanyaBratashchuk commented on src/components/TodoList/TodoList.tsx
> +            todo={todo as TodoType}
```suggestion
            todo={todo}
```

2024-05-12 12:17 UTC, anastasiiavorobiova approved these changes
Great work!

2024-12-10 17:53 UTC, closed without merging