first solution
mate-academy/react_dynamic-list-of-todos pull request #237
Opened 2020-09-10 16:34 UTC by krajnova

[DEMO LINK](https://krajnova.github.io/react_dynamic-list-of-todos/)

2020-09-11 11:49 UTC, AnastasiiaBortnichuk approved these changes

2020-09-11 14:29 UTC, irenhh commented
enable interacting with checkbox

2020-09-11 14:30 UTC, irenhh commented on src/components/CurrentUser/CurrentUser.jsx
> +    name: null,
use the same data type

2020-09-15 07:26 UTC, vsm2k17 requested changes
<img width="842" alt="Screenshot 2020-09-14 at 22 20 20" src="https://user-images.githubusercontent.com/35385361/93128650-7c7a9a80-f6d8-11ea-99c6-ff17d455a256.png">
it would be good if the text filtering worked along with the select status

2020-09-15 07:26 UTC, vsm2k17 commented on src/App.jsx
> +    todosFromServer: [],
no need to store two arrays of todos

2025-01-27 11:13 UTC, closed without merging