Develop
mate-academy/react_dynamic-list-of-todos pull request #2400
Opened 2024-06-03 07:53 UTC by przwojwwp

[DEMO LINK](https://przwojwwp.github.io/react_dynamic-list-of-todos/)

2024-06-03 15:37 UTC, natalia-klonowska requested changes
Great work 🔥 just add error handling when fetching data because now you have infinite loader ;)

2024-06-03 15:37 UTC, natalia-klonowska commented on src/App.tsx
> +    };
you should be able to catch errors if fetch fails

2024-06-06 11:44 UTC, natalia-klonowska requested changes

2024-06-06 11:44 UTC, natalia-klonowska commented on src/components/TodoModal/useTodoModal.ts
> +        setIsLoading(false);
here you also need error handling ;) remember to always handle failures in your asynchronous code to ensure a better user experience and prevent uncaught errors

2024-06-07 10:38 UTC, BogdanMaliuta reviewed
Nice!

2024-06-07 10:38 UTC, BogdanMaliuta approved these changes

2024-10-10 12:37 UTC, closed without merging