add react dynamic list
mate-academy/react_dynamic-list-of-todos pull request #2487
Opened 2024-07-19 16:55 UTC by Fetrw

[DEMO LINK](https://Fetrw.github.io/react_dynamic-list-of-todos/)

2024-07-19 18:51 UTC, etojeDenys requested changes

2024-07-19 18:51 UTC, etojeDenys commented on src/App.tsx
> +  const [filteredTodos, setFilteredTodos] = useState<Todo[]>([]);
try to rewrite it without using the separate state for filteredTodos

2024-07-19 18:51 UTC, etojeDenys commented on src/components/TodoModal/TodoModal.tsx
> +  todo: Todo | null;
```suggestion
  todo: Todo;
```
you render this component only if todo exists

2024-07-20 07:18 UTC, SanyaBratashchuk approved these changes

2026-01-16 17:46 UTC, closed without merging