Develop
mate-academy/react_dynamic-list-of-todos pull request #2489
Opened 2024-07-20 20:51 UTC by BoGoBooM

[DEMO LINK](https://bogoboom.github.io/react_dynamic-list-of-todos/)

2024-07-21 06:34 UTC, etojeDenys requested changes
demo link doesn't work, feel free to ask for some help with that in the chat

2024-07-21 20:05 UTC, BoGoBooM commented
For some reason, my task failed after the deployment, I'll ask in the chat how to fix it and tomorrow I'll fix all the errors...

2024-07-21 20:19 UTC, vadiimvooo requested changes
Please try to fix deploy issues and then re request review again. Don’t hesitate to ask for help in fe_chat.

2024-07-22 20:17 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-07-22 20:17 UTC, volodymyr-soltys97 commented on src/components/TodoFilter/TodoFilter.tsx
> +            <option value="completed">Completed</option>
Create a enum for 'all', 'active', 'completed' and use it everywhere. Also will be better if you create array and map it here

2024-07-22 20:17 UTC, volodymyr-soltys97 commented on src/components/TodoList/TodoList.tsx
> +                  'has-text-danger': completed === false,
```suggestion
                  'has-text-success': completed,
                  'has-text-danger': !completed,
```

2024-07-24 17:54 UTC, BoGoBooM commented
I've fixed everything you said above, but I'm not sure if the deploy is okay. It's taking a very long time to build

2024-07-24 17:56 UTC, BoGoBooM commented
If there's something wrong with the deploy, tell me about it and I'll fix it. For some reason, I've been experiencing a lot of technical malfunctions lately, and I don't know why...

2024-07-24 18:04 UTC, etojeDenys approved these changes
lgtm

2025-02-17 11:46 UTC, closed without merging