Solution
mate-academy/react_dynamic-list-of-todos pull request #252
Opened 2020-09-12 06:47 UTC by 1nsider21

- [DEMO LINK](https://1nsider21.github.io/react_dynamic-list-of-todos/)

2020-09-13 12:09 UTC, YuriiRysyn approved these changes
Good job!

2020-09-13 12:09 UTC, YuriiRysyn commented on src/components/TodoList/TodoList.jsx
> +            key={todo.id}
key бажано ставити першим атрибутом)

2020-09-13 12:09 UTC, YuriiRysyn commented on src/api.js
> +const API_USERS = 'https://mate-api.herokuapp.com/users';
Я думаю, гарніше було б створити один API BASIC 'https://mate-api.herokuapp.com/ і від нього відштовхуватись) 
Але це дрібниці)

2020-09-14 19:15 UTC, vsm2k17 requested changes
<img width="848" alt="Screenshot 2020-09-14 at 21 29 16" src="https://user-images.githubusercontent.com/35385361/93123818-5b627b80-f6d1-11ea-8616-29b208d05138.png">
it would be good if the text filtering worked along with the select status

2020-09-15 07:25 UTC, vsm2k17 approved these changes

2020-09-15 07:25 UTC, vsm2k17 commented on src/App.jsx
> +    user: {},
user: null

2023-08-22 11:52 UTC, closed without merging