solution
mate-academy/react_dynamic-list-of-todos pull request #300
Opened 2020-11-07 16:41 UTC by zkhomer

[DEMO LINK](https://zkhomer.github.io/react_dynamic-list-of-todos/)

2020-11-09 15:47 UTC, obashmakov requested changes

2020-11-09 15:47 UTC, obashmakov commented on src/components/CurrentUser/CurrentUser.jsx
> +      });
тут и componentDidUpdate повторяеться код. Можно вынести в отдельную функцию https://youtu.be/qwKJ-CmIZes?t=115

2020-11-09 15:47 UTC, obashmakov commented on src/components/TodoList/TodoList.jsx
> +    <div className="TodoList">
кажется получился немного большой компонент, думаю лучше будет его разбить на несколько: Input, Select и TodoItem

2020-11-09 17:25 UTC, obashmakov approved these changes

2020-11-11 12:30 UTC, danheim commented
![image](https://user-images.githubusercontent.com/36257947/98812052-7bd95880-242a-11eb-9b3e-122784df7f4e.png)
Должен подсвечиваться только выбранный юзер

2020-11-11 12:34 UTC, danheim requested changes

2020-11-11 12:34 UTC, danheim commented on src/components/TodoList/TodoList.jsx
> +                ? 'checked' : 'unchecked'}`}
npm classnames

2020-11-11 12:34 UTC, danheim commented on src/components/api.js
> +};
используешь await для fetch, используй и для .json()

2020-11-11 12:34 UTC, danheim commented on src/components/api.js
> +    .then(result => result.data);
await

2024-09-11 13:19 UTC, closed without merging