Fs may19 olha
mate-academy/react_dynamic-list-of-todos pull request #42
Opened 2019-07-08 14:56 UTC by OlgaLyubicheva

2019-07-09 08:06 UTC, vpolets requested changes
Загалом добре, але тіршки перероби логіку, виведи в таблицю все і мінімізуй повтори коду в місцях де це можливо. cursor: poiter на заголовки на кинь, юзер має знати, що це клікабельно. Дякую!)

2019-07-09 08:06 UTC, vpolets commented on src/components/TodoList.js
> +      />
три компонента відрізняються всього одним пропсом і стільки повторення коду, а коли їх стане більше? ну наприклад з'являться додаткові колонки, а в колонок додатковий функціонал, тобі щоб додати новий функціонал треба буде міняти код одразу в кількох місцяхю Не те щоб це неефективно, це збльшує імовірність помилок в коді

2019-07-09 08:06 UTC, vpolets commented on src/components/changeCompleted.js
> +  func({ todos: [...todos] });
що робить ця функція? Я як сторонній розробник знайшов цей файл і хочу його використати у свому проекті, як це працює?

2019-07-16 06:38 UTC, vpolets requested changes

2019-07-16 06:38 UTC, vpolets commented on src/App.js
> +    renderButton: true,
відобразити кнопку? Що за кнопка? Я, як колега програміст, не розумію, що це за кнопка

2019-07-16 06:38 UTC, vpolets commented on src/App.js
> +    const loadButton = document.querySelector('.load-button');
Еее ні:) З DOM напряму в Реакт ми не працюємо, позбудься цього

2019-07-16 06:38 UTC, vpolets commented on src/App.js
> +    loadButton.textContent = 'Loading...';
18-19 рядки також непотрібні, роби все через state

2019-07-16 06:38 UTC, vpolets commented on src/components/TodoItem.js
> +  todos.splice(index, 1, todo);
Це мутація вхідних даних. Якщо хочеш робити splice роби перед цим копію

2019-07-16 06:38 UTC, vpolets commented on src/components/TodoItem.js
> +      <User {...user} />
👍

2019-07-16 06:38 UTC, vpolets commented on src/components/TodoList.js
> +    switch (fieldOfSort) {
Зроби через об'єкт, де ключі будуть `fieldOfSort`, а `value` відповідні колбеки і тоді 
`funcSort = getSortMethod[fieldOfSort]`

2019-07-16 06:38 UTC, vpolets commented on src/components/TodoList.js
> +  sort = (fieldOfSort, todos, sortWay) => {
якщо це метод класу він може мати доступ до todos та sortWay без передачі їх в параметри. До чого я веду, або винось її з класу тоді, або надавай їй доступ напряму. Тобто все що тобі треба передавати в параметри це `fieldOfSort `

2019-07-16 06:38 UTC, vpolets commented on src/components/TodoList.js
> +                key={`keyTodo${todo.id}`}
а todo.id не достатньо унікальне значення?

2019-07-16 09:43 UTC, OlgaLyubicheva commented on src/App.js
> +    loadButton.textContent = 'Loading...';
я честно исправляла через event и state, но теперь сама не найду где >_< 
видимо спать надо больше )
исправлю

2019-07-17 15:20 UTC, vkryvytskyi approved these changes

2025-06-05 14:20 UTC, closed without merging