task is completed
mate-academy/react_dynamic-list-of-todos pull request #500
Opened 2021-08-02 17:02 UTC by OleksiiBlezniuk

[DEMO LINK](https://oleksiiblezniuk.github.io/react_dynamic-list-of-todos/)

2021-08-02 18:07 UTC, Artem20201610 requested changes
не работает фильтрация: [https://prnt.sc/1iffa0r](url)
не обрабатываються ситуации с отсутсвующими пользователями [https://prnt.sc/1iffmpr](url)

2021-08-03 15:15 UTC, Artem20201610 approved these changes

2021-08-04 07:02 UTC, ArtemTopolskyi requested changes

2021-08-04 07:02 UTC, ArtemTopolskyi commented on src/App.jsx
> +    visibleTodos: [],
если оставить так как сейчас - то тебе придется пересчитывать два массива при каждом изменении todos, это неоптимально

2021-08-04 08:20 UTC, ArtemTopolskyi approved these changes

2023-04-11 13:38 UTC, closed without merging