Solution
mate-academy/react_dynamic-list-of-todos pull request #69
Opened 2019-09-23 17:04 UTC by amserhii11

https://amserhii11.github.io/react_dynamic-list-of-todos

2019-09-23 17:19 UTC, amserhii11 commented
> https://amserhii11.github.io/react_dynamic-list-of-todos

Не розумію чому, у меня проблеми при загрузці сайту. При натисканні на кнопку воно не з першого разу загружає мій список. І помилка не вибиває. 
Якщо обновляти сторінку і знову натискати, то з н-ного разу все запускає.

2019-09-25 11:31 UTC, irenhh commented
after reloading the page, everything breaks and I get 200 errors in console
![image](https://user-images.githubusercontent.com/33497431/65597185-32694800-dfa1-11e9-8200-252941e60e13.png)

2019-09-25 11:37 UTC, irenhh commented
it related to propTypes in User component

2019-09-25 11:49 UTC, amserhii11 commented
> after reloading the page, everything breaks and I get 200 errors in console
> ![image](https://user-images.githubusercontent.com/33497431/65597185-32694800-dfa1-11e9-8200-252941e60e13.png)

Я вище так і написав, що там помилка вибиває, але я не розумію чого :face_with_head_bandage:  

Але якби ти перезагрузила ще разів 5-6, то воно б все окей загрузило.

2019-09-26 06:49 UTC, irenhh commented
write fetching data with `Promise.all`

2019-09-30 10:06 UTC, danheim requested changes

2019-09-30 10:06 UTC, danheim commented on src/App.js
> +      todos: prevState.todos.sort((a, b) => (a.title > b.title ? 1 : -1)),
строки сравниваем через `localCompare`

2019-09-30 10:06 UTC, danheim commented on src/api/getTodos.js
> +export const getTodos = () => fetch(`https://jsonplaceholder.typicode.com/todos`).then(response => response.json());
```suggestion
export const getTodos = () => fetch(`https://jsonplaceholder.typicode.com/todos`)
  .then(response => response.json());
```

2019-09-30 10:06 UTC, danheim commented on src/api/getUsers.js
> +export const getUsers = () => fetch(`https://jsonplaceholder.typicode.com/users`).then(response => response.json());
```suggestion
export const getUsers = () => fetch(`https://jsonplaceholder.typicode.com/users`)
  .then(response => response.json());
```

2019-09-30 10:06 UTC, danheim commented on src/App.js
> +        this.setState({ todos: data[0], users: data[1], isLoading: false });
```suggestion
        this.setState({
          todos: data[0],
          users: data[1],
          isLoading: false
        });
```
читаемость

2019-09-30 10:06 UTC, danheim commented on src/App.js
> +    const preparedTodos=getTodosWithUsers(this.state.todos, this.state.users)
линтер не мог пропустить такую строку + деструктуризация `this.state`

2019-09-30 10:06 UTC, danheim commented on src/App.js
> +        {this.state.hasError && (
деструктуризация `this.state`

2019-09-30 10:06 UTC, danheim commented on src/App.js
> +              {this.state.isLoading ? (
деструктуризация this.state

2019-09-30 10:06 UTC, danheim commented on src/App.js
> +        {this.state.todos.length === 0 ? (
деструктуризация this.state

2019-09-30 10:06 UTC, danheim commented on src/App.js
> +            {this.state.isLoading ? (
деструктуризация this.state

2019-09-30 10:06 UTC, danheim commented on src/Components/ToDoItem/ToDoItem.js
> +    user: PropTypes.object,
опиши объект

2019-09-30 10:06 UTC, danheim commented on src/Components/ToDoItem/ToDoItem.js
> +  return (
стрелочная функция

2019-09-30 10:06 UTC, danheim commented on src/Components/ToDoList/ToDoList.js
> +  return (
стрелочная функция

2019-09-30 10:06 UTC, danheim commented on src/Components/ToDoList/ToDoList.js
> +  todos: PropTypes.arrayOf(PropTypes.object).isRequired,
опиши объект

2019-09-30 10:06 UTC, danheim commented on src/Components/User/User.js
> +  return (
стрелочная функция

2019-09-30 10:06 UTC, danheim commented
У тебя установлен линтер? Если да, то `--no-verify` мы не делаем

2019-09-30 17:27 UTC, amserhii11 commented on src/api/getTodos.js
> +export const getTodos = () => fetch(`https://jsonplaceholder.typicode.com/todos`).then(response => response.json());
У меня линтер ставит это назад на место.

2019-10-01 11:16 UTC, danheim requested changes

2019-10-01 11:16 UTC, danheim commented on src/App.js
> +      todos: prevState.todos.sort((a, b) => (a.title > b.title ? 1 : -1)),
не исправлено

2019-10-01 11:16 UTC, danheim commented on src/App.js
> +      todos: prevState.todos.sort((a, b) => (a.completed < b.completed ? 1 : -1)),
метод `sort` меняет исходный массив, используй `[...prevState.todos]`
удивляюсь как это сейчас работает нормально
исправь также в других использованиях

2019-10-01 11:16 UTC, danheim commented on src/App.js
> +        {this.state.hasError && (
не исправлено

2019-10-01 11:16 UTC, danheim commented on src/App.js
> +            {this.state.isLoading ? (
не исправлено

2019-10-01 11:16 UTC, danheim commented on src/Components/ToDoItem/ToDoItem.js
> +    user: PropTypes.object,
не исправлено

2019-10-01 11:16 UTC, danheim commented on src/Components/ToDoList/ToDoList.js
> +        user: PropTypes.object,
опиши объект

2019-10-01 11:16 UTC, danheim commented on src/Components/User/User.js
> +  return (
не исправлено

2019-10-01 11:16 UTC, danheim commented on src/api/getTodos.js
> +export const getTodos = () => fetch(`https://jsonplaceholder.typicode.com/todos`).then(response => response.json());
ок

2019-10-02 10:09 UTC, danheim requested changes

2019-10-02 10:09 UTC, danheim commented on src/App.js
> +      todos: [...prevState.todos].sort((a, b) => (a.user.localCompare(b.user) === 1 ? 1 : -1)),
`user` это объект, `localCompare` используется для сравнения строковых значений
```suggestion
      todos: [...prevState.todos]
        .sort((a, b) => a.user.name.localCompare(b.user.name)),
```

2019-10-02 10:09 UTC, danheim commented on src/Components/ToDoItem/ToDoItem.js
> +    user: PropTypes.object,
не исправлено

2019-10-07 11:56 UTC, irenhh approved these changes

2025-09-02 14:29 UTC, closed without merging