solution
mate-academy/react_dynamic-list-of-todos pull request #730
Opened 2022-02-03 19:13 UTC by vladyslav-harkusha

[DEMO LINK](https://vladyslav-harkusha.github.io/react_dynamic-list-of-todos/)

2022-02-04 14:57 UTC, JHesher approved these changes

2022-02-04 18:39 UTC, Elena-brv requested changes
no very good to see it while the user info is loading
![image](https://user-images.githubusercontent.com/64437769/152584243-ee9a3ec8-a383-4eb1-a0b6-1fd4f4255367.png)

2022-02-04 18:39 UTC, Elena-brv commented on src/App.tsx
> +            .then(todos => {
better use async/await

2022-02-04 18:39 UTC, Elena-brv commented on src/api/api.ts
> +export const filterTodos = (completed: boolean): Promise<Todo[]> => (
```suggestion
export const getFilteredTodosByStatus = (completed: boolean): Promise<Todo[]> => (
```

2022-02-04 18:39 UTC, Elena-brv commented on src/components/CurrentUser/CurrentUser.tsx
> +      email: '',
why do you need to write it here?

2022-02-08 15:49 UTC, Denchepornyuk approved these changes

2022-11-01 14:42 UTC, closed without merging