Develop
mate-academy/react_dynamic-list-of-todos pull request #744
Opened 2022-02-09 14:53 UTC by gnosis-frog

[DEMO LINK](https://gnosis-frog.github.io/react_dynamic-list-of-todos/)

2022-02-10 10:53 UTC, andrii-koptiev commented
1. Когда выбираешь в селекторе например актив и потом опять All => ничего не рендериться на странице
2. Когда выбрал юзера и потом нажал Clear => 
   - не пропадает надпись SelectedUser с номером юзера
   - кнопка выбора юзера в TodoList перестает нажиматься и уже нельзя выбрать юзера повторно

2022-02-14 09:10 UTC, Elena-brv requested changes
- if the user wasn't found, the information about previous use is still shown 
- and the same problem as on this video (from 40 second)
https://www.loom.com/share/250f11996a2746e4a81ae13a0f01cd33

2022-02-14 09:10 UTC, Elena-brv commented on src/components/CurrentUser/CurrentUser.tsx
> +  async componentDidUpdate(prevProps: Props) {
```suggestion
  componentDidUpdate(prevProps: Props) {
```

2022-02-14 09:10 UTC, Elena-brv commented on src/components/TodoList/TodoList.tsx
> +      todo.title.toLowerCase().includes(searchInput.toLowerCase())
make a separate variable for `searchInput.toLowerCase()` before filtering, no need to do this operation on every iteration

2023-02-08 10:49 UTC, closed without merging