Develop
mate-academy/react_dynamic-list-of-todos pull request #771
Opened 2022-04-06 00:34 UTC by SanyaBratashchuk

[DEMO LINK](https://SanyaBratashchuk.github.io/react_dynamic-list-of-todos/)

2022-04-12 10:12 UTC, solaryasha commented on src/App.tsx
> +  };
useMemo

2022-04-12 10:22 UTC, solaryasha requested changes

2022-04-12 10:22 UTC, solaryasha commented on src/App.tsx
> +  };
З appliedQuery в залежностях

2022-04-12 10:22 UTC, solaryasha commented on src/App.tsx
> +  };
useCallback

2022-04-12 10:22 UTC, solaryasha commented on src/components/CurrentUser/CurrentUser.scss
> +
Don't leave comments

2022-04-12 10:22 UTC, solaryasha commented on src/components/CurrentUser/CurrentUser.tsx
> +        }}
```suggestion
        onClick={clearUser}
```

2022-04-12 10:22 UTC, solaryasha commented on src/components/CurrentUser/CurrentUser.tsx
> +
Варто щось показувати, поки не завантажився користувач. Можна Loader

2022-04-12 10:22 UTC, solaryasha commented on src/components/TodoList/TodoList.tsx
> +/* eslint-disable jsx-a11y/label-has-associated-control */
Why do you need this ?

2022-04-12 10:22 UTC, solaryasha commented on src/components/TodoList/TodoList.tsx
> +  changeQuery: (...args: any[]) => void,
Опиши явно тип, погугли setStateAction type

2022-04-12 10:22 UTC, solaryasha commented on src/components/TodoList/TodoList.tsx
> +    randomizeTodos,
Краще мати стейт для інпутів і селекту в цьому компоненті

2022-04-13 06:03 UTC, SanyaBratashchuk commented
> [DEMO LINK](https://SanyaBratashchuk.github.io/react_dynamic-list-of-todos/)

Демо лінка не оновлюється(

2022-04-13 10:54 UTC, solaryasha approved these changes
Крутий лоадер ! Well done !

2022-04-13 10:54 UTC, solaryasha commented on src/App.tsx
> +  );
🔥

2026-05-02 10:22 UTC, closed without merging