(React) dynamic-list-of-todos
mate-academy/react_dynamic-list-of-todos pull request #784
Opened 2022-04-13 12:52 UTC by Ostafii4uk

[DEMO LINK](https://ostafii4uk.github.io/react_dynamic-list-of-todos/)

2022-04-13 16:38 UTC, jstmpelowycz commented on src/App.tsx
> +      });
You might have missed one of the requirements in technical task:
*User component receives userId as a prop and loads user details from [GET user endpoint](https://mate.academy/students-api/users/1) (replace 1 with a given userId)*

2022-04-13 16:50 UTC, jstmpelowycz requested changes
A few things to reflect upon and commit changes, good job though!!

2022-04-13 16:50 UTC, jstmpelowycz commented on src/App.tsx
> +              users={users}
In accordance to the comment above, you shouldn't have passed `users` to `User`, two down below only

2022-04-13 16:50 UTC, jstmpelowycz commented on src/components/CurrentUser/CurrentUser.tsx
> +          {result?.id}
```suggestion
          {`Selected user: ${result?.id}`}
```

2022-04-13 16:50 UTC, jstmpelowycz commented on src/components/TodoList/TodoList.tsx
> +            return todo;
I would recommend using enum

2022-04-13 16:50 UTC, jstmpelowycz commented on src/components/TodoList/TodoList.tsx
> +          </option>
Simplify your own code, read [this](https://stackoverflow.com/questions/55601342/using-enumerations-in-react-select)

2022-04-13 16:50 UTC, jstmpelowycz commented on src/components/TodoList/TodoList.tsx
> +              ))}
```suggestion
              className={classnames('TodoList__item', (todo.completed
                  ? 'TodoList__item--checked' 
                  : 'TodoList__item--unchecked'
              ))}
```

2022-04-13 16:50 UTC, jstmpelowycz commented on src/react-app-env.d.ts
> +  updatedAt?: string,
These are not necessary here and down below in `User` type

2022-04-18 11:37 UTC, Ihor-Karpyn approved these changes

2022-04-18 19:52 UTC, closed without merging