dynamic list of todos was created
mate-academy/react_dynamic-list-of-todos pull request #821
Opened 2022-05-23 13:12 UTC by Anastasiia-Svintsova

[DEMO LINK](https://Anastasiia-Svintsova.github.io/react_dynamic-list-of-todos/)

2022-05-24 06:46 UTC, Vakolyyk approved these changes
Cool

2022-05-24 08:46 UTC, danylo-onishchuk requested changes

2022-05-24 08:46 UTC, danylo-onishchuk commented on src/api/api.ts
> +    const data = await response.json();
json() не возвращает промис

2022-05-24 08:46 UTC, danylo-onishchuk commented on src/components/TodoList/TodoList.tsx
> +          />
create method

2022-05-25 09:43 UTC, danylo-onishchuk approved these changes

2023-04-24 14:47 UTC, closed without merging