solution
mate-academy/react_dynamic-list-of-todos pull request #864
Opened 2022-06-15 21:22 UTC by yelnikov-andrii

[DEMO LINK](https://yelnikov-andrii.github.io/react_dynamic-list-of-todos/)

2022-06-17 14:55 UTC, ZUBOV-ILLIA approved these changes
Good Job!

2022-06-20 10:07 UTC, Denchepornyuk commented
![Screenshot 2022-06-20 at 13 06 54](https://user-images.githubusercontent.com/37452763/174578969-5ee798bb-57ae-4c07-9dff-337ccf4477e7.png)

all buttons with the same user should be selected if one of them selected

2022-06-20 10:17 UTC, Denchepornyuk requested changes

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +  const urlTodos = 'https://mate.academy/students-api/todos';
move all login with fetch to separate file
create file api/api.ts and move fetch to this file

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +  }]);
```suggestion
  const [todos, setTodos] = useState();
```

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +  const [theTodos, setTheTodos] = useState([{
add type for todos

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +        } else {
move to api file

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +        response.json()
move to api file

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +              return todo.title.includes(inputedValue);
don't forget to handle lower and upper cases

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +              }
use switch case

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +            const selected = [...todos].filter((todo) => {
you don't have to make an array copy, filter is immutable method

2022-06-20 10:17 UTC, Denchepornyuk commented on src/App.tsx
> +          .then(todos => {
move to api file

2022-06-20 10:17 UTC, Denchepornyuk commented on src/components/CurrentUser/CurrentUser.tsx
> +  const urlUser = `https://mate.academy/students-api/users/${userId}`;
move to api file

2022-06-20 10:17 UTC, Denchepornyuk commented on src/components/CurrentUser/CurrentUser.tsx
> +          });
move to api file

2022-06-20 10:17 UTC, Denchepornyuk commented on src/components/CurrentUser/CurrentUser.tsx
> +  );
```suggestion
  const [user, setUser] = useState(null);
```
user can be null, add type for user

2022-06-20 10:17 UTC, Denchepornyuk commented on src/components/CurrentUser/CurrentUser.tsx
> +            <h2 className="CurrentUser__title"><span>{`Selected user: ${user.id}`}</span></h2>
don't write code in one line

2022-06-20 10:17 UTC, Denchepornyuk commented on src/components/CurrentUser/CurrentUser.tsx
> +      && user.email === '' && user.phone === '' ? ('User not found') : (
check only user instead of all these fields

2022-06-20 10:17 UTC, Denchepornyuk commented on src/components/TodoList/TodoList.tsx
> +          value={inputedValue}
this form shoudn't be in TodoList component

2022-06-20 10:17 UTC, Denchepornyuk commented on src/components/TodoList/TodoList.tsx
> +          onClick={onSorted}
use onSubmit in form instead of onClick in button

2022-06-23 08:17 UTC, Denchepornyuk approved these changes

2022-06-23 08:17 UTC, Denchepornyuk commented on src/App.tsx
> +        const selected = [...todos].filter((todo) => {
you don't have to make an array copy, filter is immutable method

2024-03-19 15:12 UTC, closed without merging